/// Flutter icons BightSettingsIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BightSettingsIcons
///      fonts:
///       - asset: fonts/BightSettingsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BightSettingsIcons {
  BightSettingsIcons._();

  static const _kFontFam = 'BightSettingsIcons';
  static const _kFontPkg = null;

  static const IconData pie_chart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData funnel_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
