/// Flutter icons BightVideoIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BightVideoIcons
///      fonts:
///       - asset: fonts/BightVideoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BightVideoIcons {
  BightVideoIcons._();

  static const _kFontFam = 'BightVideoIcons';
  static const _kFontPkg = null;

  static const IconData custom_fast_forward = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData custom_love = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData custom_play = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData custom_remove = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData custom_info = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData custom_share = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData custom_pause = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData custom_fast_rewind = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData custom_fast_forward_1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData custom_favorite = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData custom_pin = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_flip = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
