/// Flutter icons WorkspaceIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WorkspaceIcons
///      fonts:
///       - asset: fonts/WorkspaceIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WorkspaceIcons {
  WorkspaceIcons._();

  static const _kFontFam = 'WorkspaceIcons';
  static const _kFontPkg = null;

  static const IconData bight_settings = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData workspace_name = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_workspace = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spoon_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_bubble = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
